version: '3.3'
services:
  frontend:
    build: Dockerfile_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - mongo
    networks:
      - portfolio_net
  mongo:
    build: Dockerfile_mongo
    restart: always
    networks:
      - portfolio_net
  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - portfolio_net
volumes:
  mongo_data:
networks:
  portfolio_net:
    external: true
