version: '3.3'
services:
  frontend:
    build: 
      dockerfile: Dockerfile_nginx
      context: .
    ports:
      - "80:80"
    depends_on:
      - backend
      - mongo-0.mongodb-headless
    networks:
      - portfolio_net
  mongo-0.mongodb-headless:
    build: 
      dockerfile: Dockerfile_mongo
      context: .
    restart: always
    networks:
      - portfolio_net
  backend:
    build: .
    depends_on:
      - mongo-0.mongodb-headless
    # ports:
    #   - "5000:5000"
    networks:
      - portfolio_net
volumes:
  mongo_data:
networks:
  portfolio_net:
    external: true
