architecture: replicaset
replicaCount: 1
auth:
  enabled: true
  rootUser: root
  rootPassword: "itay"
  databases: [ "employees","tasks" ]
  usernames: [ "root","root" ]
  passwords: [ "itay","itay" ]
replicaSetName: rs0
#when im adding this the container is not up
# extraVolumeMounts:
#   - name: extras
#     mountPath: /data/db
replicaSetHostnames: true
image:
  tag: 5.0.9
initdbScripts:
  initdb-script.js: |
    db.createUser({
      user: 'root',
      pwd: 'itay',
      roles: [
        {
          role: 'readWrite',
          db: 'employees',
        },
        {
          role: 'readWrite',
          db: 'tasks',
        },
      ]});
    dbe = new Mongo().getDB("employees");
    dbt = new Mongo().getDB("tasks");
    dbe.createCollection('employees', { capped: false });
    dbt.createCollection('tasks', { capped: false });
    dbe.employees.insert([{
      "id": NumberInt(1),
      "first_name": "Shana",
      "last_name": "Mucklestone",
      "email": "smucklestone0@goo.ne.jp",
      "department_name": "Engineering"
    }, {
      "id": NumberInt(2),
      "first_name": "Egon",
      "last_name": "McGilleghole",
      "email": "emcgilleghole1@purevolume.com",
      "department_name": "Services"
    }, {
      "id": NumberInt(3),
      "first_name": "Elia",
      "last_name": "Snoday",
      "email": "esnoday2@arstechnica.com",
      "department_name": "Human Resources"
    }, {
      "id": NumberInt(4),
      "first_name": "Derril",
      "last_name": "Ludlom",
      "email": "dludlom3@reuters.com",
      "department_name": "Marketing"
    }, {
      "id": NumberInt(5),
      "first_name": "Noell",
      "last_name": "Toffanini",
      "email": "ntoffanini4@sogou.com",
      "department_name": "Services"
    }, {
      "id": NumberInt(6),
      "first_name": "Paolina",
      "last_name": "Kurtis",
      "email": "pkurtis5@slashdot.org",
      "department_name": "Engineering"
    }, {
      "id": NumberInt(7),
      "first_name": "Mahmud",
      "last_name": "Leppingwell",
      "email": "mleppingwell6@pcworld.com",
      "department_name": "Marketing"
    }, {
      "id": NumberInt(8),
      "first_name": "Emera",
      "last_name": "Giffkins",
      "email": "egiffkins7@ehow.com",
      "department_name": "Support"
    }, {
      "id": NumberInt(9),
      "first_name": "Lutero",
      "last_name": "Bog",
      "email": "lbog8@hubpages.com",
      "department_name": "Business Development"
    }, {
      "id": NumberInt(10),
      "first_name": "Inigo",
      "last_name": "Cawsy",
      "email": "icawsy9@google.com.br",
      "department_name": "Product Management"
    }]);

    dbt.tasks.insert([{
      "id": NumberInt(1),
      "employee_id": NumberInt(20),
      "description": "Evaluate the market",
      "due_date": "06/07/2022"
    }, {
      "id": NumberInt(2),
      "employee_id": NumberInt(12),
      "description": "New product development template",
      "due_date": "20/09/2022"
    }, {
      "id": NumberInt(3),
      "employee_id": NumberInt(12),
      "description": "Produce lab scale product",
      "due_date": "07/06/2022"
    }, {
      "id": NumberInt(4),
      "employee_id": NumberInt(16),
      "description": "Determine safety issues",
      "due_date": "17/08/2022"
    }, {
      "id": NumberInt(5),
      "employee_id": NumberInt(20),
      "description": "Analyze the competition",
      "due_date": "30/06/2022"
    }, {
      "id": NumberInt(6),
      "employee_id": NumberInt(9),
      "description": "Determine safety issues",
      "due_date": "06/05/2022"
    }, {
      "id": NumberInt(7),
      "employee_id": NumberInt(16),
      "description": "New product development template",
      "due_date": "16/09/2022"
    }, {
      "id": NumberInt(8),
      "employee_id": NumberInt(11),
      "description": "Review legal issues",
      "due_date": "31/01/2022"
    }, {
      "id": NumberInt(9),
      "employee_id": NumberInt(5),
      "description": "New product development template",
      "due_date": "04/02/2022"
    }, {
      "id": NumberInt(10),
      "employee_id": NumberInt(1),
      "description": "Evaluate internal product",
      "due_date": "04/06/2022"
    }, {
      "id": NumberInt(11),
      "employee_id": NumberInt(7),
      "description": "Produce lab scale product",
      "due_date": "20/02/2022"
    }, {
      "id": NumberInt(12),
      "employee_id": NumberInt(3),
      "description": "Produce lab scale product",
      "due_date": "21/06/2022"
    }, {
      "id": NumberInt(13),
      "employee_id": NumberInt(1),
      "description": "New product development template",
      "due_date": "10/06/2022"
    }, {
      "id": NumberInt(14),
      "employee_id": NumberInt(9),
      "description": "Produce lab scale product",
      "due_date": "02/02/2022"
    }, {
      "id": NumberInt(15),
      "employee_id": NumberInt(16),
      "description": "Evaluate the market",
      "due_date": "07/02/2022"
    }, {
      "id": NumberInt(16),
      "employee_id": NumberInt(14),
      "description": "Assess manufacturing capabillities",
      "due_date": "07/02/2022"
    }, {
      "id": NumberInt(17),
      "employee_id": NumberInt(15),
      "description": "Evaluate the market",
      "due_date": "07/09/2022"
    }, {
      "id": NumberInt(18),
      "employee_id": NumberInt(16),
      "description": "Analyze the competition",
      "due_date": "05/03/2022"
    }, {
      "id": NumberInt(19),
      "employee_id": NumberInt(20),
      "description": "Evaluate internal product",
      "due_date": "23/08/2022"
    }, {
      "id": NumberInt(20),
      "employee_id": NumberInt(1),
      "description": "Determine safety issues",
      "due_date": "24/07/2022"
    }, {
      "id": NumberInt(21),
      "employee_id": NumberInt(5),
      "description": "Analyze the competition",
      "due_date": "14/02/2022"
    }, {
      "id": NumberInt(22),
      "employee_id": NumberInt(14),
      "description": "Analyze the competition",
      "due_date": "15/04/2022"
    }, {
      "id": NumberInt(23),
      "employee_id": NumberInt(17),
      "description": "New product development template",
      "due_date": "20/08/2022"
    }, {
      "id": NumberInt(24),
      "employee_id": NumberInt(15),
      "description": "Analyze the competition",
      "due_date": "03/07/2022"
    }, {
      "id": NumberInt(25),
      "employee_id": NumberInt(6),
      "description": "Evaluate the market",
      "due_date": "12/07/2022"
    }, {
      "id": NumberInt(26),
      "employee_id": NumberInt(20),
      "description": "Evaluate internal product",
      "due_date": "19/07/2022"
    }, {
      "id": NumberInt(27),
      "employee_id": NumberInt(3),
      "description": "Analyze the competition",
      "due_date": "14/02/2022"
    }, {
      "id": NumberInt(28),
      "employee_id": NumberInt(9),
      "description": "Produce lab scale product",
      "due_date": "02/07/2022"
    }, {
      "id": NumberInt(29),
      "employee_id": NumberInt(14),
      "description": "Determine safety issues",
      "due_date": "23/01/2022"
    }, {
      "id": NumberInt(30),
      "employee_id": NumberInt(13),
      "description": "Analyze the competition",
      "due_date": "18/03/2022"
    }]);}, {
      "id": NumberInt(2),
      "employee_id": NumberInt(12),
      "description": "New product development template",
      "due_date": "20/09/2022"
    }, {
      "id": NumberInt(3),
      "employee_id": NumberInt(12),
      "description": "Produce lab scale product",
      "due_date": "07/06/2022"
    }, {
      "id": NumberInt(4),
      "employee_id": NumberInt(16),
      "description": "Determine safety issues",
      "due_date": "17/08/2022"
    }, {
      "id": NumberInt(5),
      "employee_id": NumberInt(20),
      "description": "Analyze the competition",
      "due_date": "30/06/2022"
    }, {
      "id": NumberInt(6),
      "employee_id": NumberInt(9),
      "description": "Determine safety issues",
      "due_date": "06/05/2022"
    }, {
      "id": NumberInt(7),
      "employee_id": NumberInt(16),
      "description": "New product development template",
      "due_date": "16/09/2022"
    }, {
      "id": NumberInt(8),
      "employee_id": NumberInt(11),
      "description": "Review legal issues",
      "due_date": "31/01/2022"
    }, {
      "id": NumberInt(9),
      "employee_id": NumberInt(5),
      "description": "New product development template",
      "due_date": "04/02/2022"
    }, {
      "id": NumberInt(10),
      "employee_id": NumberInt(1),
      "description": "Evaluate internal product",
      "due_date": "04/06/2022"
    }, {
      "id": NumberInt(11),
      "employee_id": NumberInt(7),
      "description": "Produce lab scale product",
      "due_date": "20/02/2022"
    }, {
      "id": NumberInt(12),
      "employee_id": NumberInt(3),
      "description": "Produce lab scale product",
      "due_date": "21/06/2022"
    }, {
      "id": NumberInt(13),
      "employee_id": NumberInt(1),
      "description": "New product development template",
      "due_date": "10/06/2022"
    }, {
      "id": NumberInt(14),
      "employee_id": NumberInt(9),
      "description": "Produce lab scale product",
      "due_date": "02/02/2022"
    }, {
      "id": NumberInt(15),
      "employee_id": NumberInt(16),
      "description": "Evaluate the market",
      "due_date": "07/02/2022"
    }, {
      "id": NumberInt(16),
      "employee_id": NumberInt(14),
      "description": "Assess manufacturing capabillities",
      "due_date": "07/02/2022"
    }, {
      "id": NumberInt(17),
      "employee_id": NumberInt(15),
      "description": "Evaluate the market",
      "due_date": "07/09/2022"
    }, {
      "id": NumberInt(18),
      "employee_id": NumberInt(16),
      "description": "Analyze the competition",
      "due_date": "05/03/2022"
    }, {
      "id": NumberInt(19),
      "employee_id": NumberInt(20),
      "description": "Evaluate internal product",
      "due_date": "23/08/2022"
    }, {
      "id": NumberInt(20),
      "employee_id": NumberInt(1),
      "description": "Determine safety issues",
      "due_date": "24/07/2022"
    }, {
      "id": NumberInt(21),
      "employee_id": NumberInt(5),
      "description": "Analyze the competition",
      "due_date": "14/02/2022"
    }, {
      "id": NumberInt(22),
      "employee_id": NumberInt(14),
      "description": "Analyze the competition",
      "due_date": "15/04/2022"
    }, {
      "id": NumberInt(23),
      "employee_id": NumberInt(17),
      "description": "New product development template",
      "due_date": "20/08/2022"
    }, {
      "id": NumberInt(24),
      "employee_id": NumberInt(15),
      "description": "Analyze the competition",
      "due_date": "03/07/2022"
    }, {
      "id": NumberInt(25),
      "employee_id": NumberInt(6),
      "description": "Evaluate the market",
      "due_date": "12/07/2022"
    }, {
      "id": NumberInt(26),
      "employee_id": NumberInt(20),
      "description": "Evaluate internal product",
      "due_date": "19/07/2022"
    }, {
      "id": NumberInt(27),
      "employee_id": NumberInt(3),
      "description": "Analyze the competition",
      "due_date": "14/02/2022"
    }, {
      "id": NumberInt(28),
      "employee_id": NumberInt(9),
      "description": "Produce lab scale product",
      "due_date": "02/07/2022"
    }, {
      "id": NumberInt(29),
      "employee_id": NumberInt(14),
      "description": "Determine safety issues",
      "due_date": "23/01/2022"
    }, {
      "id": NumberInt(30),
      "employee_id": NumberInt(13),
      "description": "Analyze the competition",
      "due_date": "18/03/2022"
    }]);
