architecture: replicaset
replicaCount: 1
auth:
  enabled: true
  rootUser: root
  rootPassword: "itay"
  databases: [ "employees","tasks" ]
  usernames: [ "root","root" ]
  passwords: [ "itay","itay" ]
replicaSetName: rs0
#when im adding this the container is not up
# extraVolumeMounts:
#   - name: extras
#     mountPath: /data/db
replicaSetHostnames: true
image:
  tag: 5.0.9
initdbScripts:
  my_init_script.js: |
    db.createUser({
      user: 'root',
      pwd: 'itay',
      roles: [
        {
          role: 'readWrite',
          db: 'employees',
        },
        {
          role: 'readWrite',
          db: 'tasks',
        },
      ]});
    dbe = new Mongo().getDB("employees");
    dbt = new Mongo().getDB("tasks");
    dbe.createCollection('employees', { capped: false });
    dbt.createCollection('tasks', { capped: false });
    dbe.employees.insert([{
        "id": 1,
        "first_name": "Shana",
        "last_name": "Mucklestone",
        "email": "smucklestone0@goo.ne.jp",
        "department_name": "Engineering"
    }]);
    dbt.tasks.insert([{
      "id": 1,
      "employee_id": 20,ex
      "description": "Evaluate the market",
      "due_date": "06/07/2022"
    }]);
