apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
  source:
    repoURL: https://github.com/dizex98/todolist.git
    targetRevision: HEAD
    path: kube/todolist
  destination:
    server: https://kubernetes.default.svc
    namespace: default


#### check how it looks on the ui when you change the helm chart