name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker compose components
      env:
        ROOT_USERNAME: ${{ secrets.ROOT_USERNAME }}
        ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      run: |
        docker network create portfolio_net
        docker-compose up -d
    
    - name: E2E Tests
      env:
        domain: localhost/tasks
      run: |
        sleep 2
        curl -X POST -F 'emp_id=20' -F 'desc="POST from jenkins"' -F 'due_date="01/01/2040"' ${{ env.domain }}
        curl ${{ env.domain }} | grep "01/01/2040" -h5
        echo "POST from jenkins has been succeeded..."
        sleep 2
        curl -X POST -F 'update_task_id=999' -F 'update_desc="PUT from jenkins"' ${{ env.domain }}
        curl ${{ env.domain }} | grep 999 -h5
        echo "PUT from jenkins has been succeeded..."
        sleep 2
        curl -X POST -F 'del_task_id=999' ${{ env.domain }}
        echo "DELETE from jenkins has been succeeded..."
        sleep 2

        