name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker compose components
      run: |
        docker network create portfolio_net
        docker-compose up --build -d
    
    - name: Testing with curl command
      run: |
        docker ps
        curl todolist_frontend_1
  
  # test:
  #   needs: build
        